set(enabled_modules
  Log
  CppMicroServices
  Core
  AppUtil
  DataTypesExt
  AlgorithmsExt
  Annotation
  BoundingShape
  ContourModel
  GraphAlgorithms
  DICOM
  DICOMQI
  Forms
  FormsUI
  ImageDenoising
  ImageExtraction
  ImageStatistics
  IOExt
  LegacyIO
  LegacyGL
  MapperExt
  Multilabel
  PlanarFigure
  QtWidgets
  QtWidgetsExt
  Remeshing
  SceneSerialization
  SceneSerializationBase
  Segmentation
  SegmentationUI
  SurfaceInterpolation
)

set(enabled_plugins
  "org.blueberry.core.commands"
  "org.blueberry.core.expressions"
  "org.blueberry.core.runtime"
  "org.blueberry.core.jobs"
  "org.blueberry.ui.qt"
  "org.blueberry.ui.qt.help"
  "org.blueberry.ui.qt.log"
  "org.mitk.core.services"
  "org.mitk.gui.common"
  "org.mitk.core.jobs"
  "org.mitk.gui.qt.application"
  "org.mitk.gui.qt.basicimageprocessing"
  "org.mitk.gui.qt.common"
  "org.mitk.gui.qt.datamanager"
  "org.mitk.gui.qt.extapplication"
  "org.mitk.gui.qt.ext"
  "org.mitk.gui.qt.imagecropper"
  "org.mitk.gui.qt.imagenavigator"
  "org.mitk.gui.qt.measurementtoolbox"
  "org.mitk.gui.qt.mitkworkbench.intro"
  "org.mitk.gui.qt.pixelvalue"
  "org.mitk.gui.qt.properties"
  "org.mitk.gui.qt.remeshing"
  "org.mitk.gui.qt.segmentation"
  "org.mitk.gui.qt.stdmultiwidgeteditor"
  "org.mitk.gui.qt.volumevisualization"
)
